version: '3.9'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    links:
      - redis-server
    environment:
      PORT: 3001
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - redis-server
